receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  
  hostmetrics: 
      collection_interval: 10s
      scrapers:
        load:
        memory:

exporters:
  otlphttp/jaeger:
    endpoint: "http://otel-jaeger:4318"
    tls:
      insecure: true
  otlp/jaeger:
    endpoint: "http://otel-jaeger:4317"
    tls:
      insecure: true

  otlphttp/loki:
    endpoint: "http://otel-loki:3100/otlp"  # Replace with your Loki endpoint
    timeout: 30s  # Increase the timeout if necessary
    tls:
      insecure: true
  
  prometheus:
    endpoint: "0.0.0.0:8889"
    # namespace: "prom"
  
  prometheusremotewrite:
    endpoint: "http://otel-prometheus:9090/api/v1/write"  # Your Prometheus endpoint
    add_metric_suffixes: true
    timeout: 30s  # Increase the timeout if necessary
    tls:
      insecure: true
  

processors:
  batch:
    timeout: 20s
  
  memory_limiter:
    # 80% of maximum memory up to 2G
    limit_mib: 1500
    # 25% of limit up to 2G
    spike_limit_mib: 512
    check_interval: 5s
  
  attributes:
    actions:
      - key: "environment"
        value: "production"  # Add custom tag with key 'environment' and value 'production'
        action: insert
      - key: "team"
        value: "backend"  # Add custom tag with key 'team' and value 'backend'
        action: insert
      - key: "region"
        value: "us-west"  # Add custom tag with key 'region' and value 'us-west'
        action: insert
  
  attributes/extract/logs:
    actions:
      - key: trace_id
        from_attribute: trace_id
        action: insert
      - key: level
        from_attribute: log.level
        action: insert


# https://github.com/open-telemetry/opentelemetry-collector/blob/main/extension/README.md
extensions:
  # responsible for responding to health check calls on behalf of the collector.
  health_check:
  # fetches the collector’s performance data
  pprof:
  # serves as an http endpoint that provides live debugging data about instrumented components.
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, attributes]
      exporters: [otlphttp/jaeger]
    logs:
      receivers: [otlp]
      processors: [batch, attributes]
      exporters: [otlphttp/loki]
    metrics:
      receivers: [otlp]
      processors: [batch, attributes, memory_limiter]
      exporters: [prometheusremotewrite]
